name: deferred_type
description: Dart algebraic data type and helper functions for working with asynchronous data.
homepage: https://github.com/arafatamim/deferred_type/tree/main/packages/deferred_type
version: 3.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1

dependencies:
  collection: ^1.16.0
